apiVersion: v1
kind: ServiceAccount
metadata:
  name: governance-policy-rbac-sync
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: governance-policy-rbac-sync-election-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: governance-policy-rbac-sync
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - policy.open-cluster-management.io
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: governance-policy-rbac-sync-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: governance-policy-rbac-sync-election-role
subjects:
- kind: ServiceAccount
  name: governance-policy-rbac-sync
  namespace: open-cluster-management-agent-addon
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: governance-policy-rbac-sync
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: governance-policy-rbac-sync
subjects:
- kind: ServiceAccount
  name: governance-policy-rbac-sync
  namespace: open-cluster-management-agent-addon
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: governance-policy-rbac-sync
spec:
  replicas: 1
  selector:
    matchLabels:
      name: governance-policy-rbac-sync
  template:
    metadata:
      labels:
        name: governance-policy-rbac-sync
    spec:
      containers:
      - args:
        - --log-level=2
        - --v=0
        command:
        - governance-policy-rbac-sync
        env:
        - name: WATCH_NAMESPACE
          value: managed
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: governance-policy-rbac-sync
        image: quay.io/open-cluster-management/governance-policy-rbac-sync:latest
        imagePullPolicy: Always
        name: governance-policy-rbac-sync
      serviceAccountName: governance-policy-rbac-sync
